// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:desafio_bus2/domain/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LocationAdapter());
    registerAdapter(TimezoneAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserDocumentAdapter());
    registerAdapter(UserGenderAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(LocationAdapter());
    registerAdapter(TimezoneAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserDocumentAdapter());
    registerAdapter(UserGenderAdapter());
  }
}
